const SoundCircleActionTypes = {
    ADD_SOUND_CIRCLE_TO_REDUX : 'ADD_SOUND_CIRCLE_TO_REDUX',
    UPDATE_SOUND_CIRCLE : 'UPDATE_SOUND_CIRCLE', 
    RESET_SOUND_CIRCLE_CONTROL_STATES : 'RESET_SOUND_CIRCLE_CONTROL_STATES',
    SET_TWEAKING_IDX : 'SET_TWEAKING_IDX',
    SET_ROTATING_IDX : 'SET_ROTATING_IDX',
    SET_VOLUMING_IDX : 'SET_VOLUMING_IDX',
    SET_PITCHING_IDX : 'SET_PITCHING_IDX',

}

export default SoundCircleActionTypes